# .streamlit/secrets.toml

[snowflake]
user = "your_user"
password = "your_password"
account = "your_account_url"  # e.g. abcde12345.us-east-1
warehouse = "COMPUTE_WH"
database = "CULTURE_DB"
schema = "PUBLIC"
role = "SYSADMIN"  # optional
